# Generated by Django 3.0.5 on 2020-08-02 09:19

from django.db import migrations, models
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=utils.get_upload_path_video)),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=64, null=True)),
                ('author', models.CharField(max_length=64, null=True)),
                ('tag', models.CharField(max_length=1024, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
