# Generated by Django 3.0.5 on 2020-08-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0002_auto_20200802_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='tag',
        ),
    ]
